### ISSUE TITLE
关于绑定两个账号怎么切换的问题

### ISSUE THREAD

**Issue by Noechofu** [blueskybone/ArkScreen#1]
大佬我看默认是选择绑定的第一个账号，我想切换第二个号（b服）找不到切换功能的位置，还是说要还token

**Comment by blueskybone** [comment]
> 大佬我看默认是选择绑定的第一个账号，我想切换第二个号（b服）找不到切换功能的位置，还是说要还token

（当时写的时候偷懒了没考虑b服用户）一个森空岛账号对应一个token，账号绑定多个游戏角色默认读列表的第一个，所以目前和森空岛设置的默认角色没有关系。或者可以进群924153470，这两天抽时间编译一个能读取默认用户的版本发群里，先用着

**Comment by blueskybone** [comment]
1.1版本已更新b服支持。需要在森空岛app切换默认绑定角色
