### ISSUE TITLE
23.11.15 自动签到失效 抓包提示版本过低

### ISSUE THREAD

**Issue by M-ls** [blueskybone/ArkScreen#5]
![S31115-17011276_com network proxy(1)](https://github.com/blueskybone/ArkScreen/assets/36070993/7615efd7-effc-4012-9c91-94acbc673940)

**Comment by blueskybone** [comment]
yj昨天把旧的请求头无效了，正在做新的验参方法的适配，具体可以看https://gitee.com/FancyCabbage/skyland-auto-sign 底部的说明
顺便问下这是哪个抓包工具

**Comment by M-ls** [comment]
proxypin 在GitHub开源 一部分小黄鸟抓不到的这个软件可以抓 自己试着抓了下看到了旧版方法的登录有ssl验证

**Comment by blueskybone** [comment]
收到
软件新版本添加了新的签名算法，可以登录了
