### ISSUE TITLE
获取实时数据显示405

### ISSUE THREAD

**Issue by czc715f** [blueskybone/ArkScreen#7]
点进实时数据的时候会显示405，无法显示数据，版本1.4.1
![Screenshot_20240912_221852_com blueskybone arkscreen](https://github.com/user-attachments/assets/717bc699-deab-4334-b613-a192c8452712)

**Comment by blueskybone** [comment]
目前还没找到问题在哪，暂时的解决方法是换个网络或者挂梯子试试

**Comment by blueskybone** [comment]
1.4.2已修复
